/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { LessonListRelationFilter } from "../../lesson/base/LessonListRelationFilter";
import { EnumCourseLevel } from "./EnumCourseLevel";
import { ProgressListRelationFilter } from "../../progress/base/ProgressListRelationFilter";

@InputType()
class CourseWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  language?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => LessonListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LessonListRelationFilter)
  @IsOptional()
  @Field(() => LessonListRelationFilter, {
    nullable: true,
  })
  lessons?: LessonListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumCourseLevel,
  })
  @IsEnum(EnumCourseLevel)
  @IsOptional()
  @Field(() => EnumCourseLevel, {
    nullable: true,
  })
  level?: "Option1";

  @ApiProperty({
    required: false,
    type: () => ProgressListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProgressListRelationFilter)
  @IsOptional()
  @Field(() => ProgressListRelationFilter, {
    nullable: true,
  })
  progresses?: ProgressListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;
}

export { CourseWhereInput as CourseWhereInput };
